### ISSUE TITLE
understanding the workflow to extract seqlet positions from chrombpnet results

### ISSUE THREAD

**Issue by sid5427** [austintwang/finemo_gpu#16]
Hello,

I am trying to understand which steps to use to extract seqlet positions for set of genome coordinates (peak regions) as part of my chrombpnet analysis.

Assume I have a full chrombpnet run done on this sample - BIAS model then the MAIN model and then generated contributions scores and then run tfmodisco to give the html report + cwm library. 

My goal is to connect the seqlet CWM identified by modico to which peak region it's coming from.
Could you walk through the steps required to get this information - appreciate if you could example file names or similar.

Thanks!

**Comment by austintwang** [comment]
Hi Sidharth,

You can extract seqlet positions from the tfmodisco output H5 file as shown here:
https://github.com/jmschrei/tfmodisco-lite?tab=readme-ov-file#running-tfmodisco-lite

`example_idx` contains the index of the region containing the seqlet. `start` and `end` contain the start and end indices of the seqlet within the input region. `is_revcomp` contains strand information. One important thing to note tfmodisco crops each input region to the center 400 base pairs, and the start and end indices are relative to the cropped region.  

If it helps, finemo_gpu contains an internal function that takes in a tfmodisco H5 file, a polars dataframe of input peaks, and outputs a polars dataframe of seqlets with genomic coordinates:
https://github.com/austintwang/finemo_gpu/blob/de31f0bf7caa96b0be5947b14d9965311069d163/src/finemo/data_io.py#L168

If you have further questions about the tfmodisco output format I suggest opening an issue here:
https://github.com/jmschrei/tfmodisco-lite/tree/main 

That being said, the set of seqlets is heavily filtered and incomplete. If you are looking for a comprehensive set of motif instances, I recommend using hit calls from this tool.

Hope this helps!

**Comment by sid5427** [comment]
Hi @austintwang 

Thanks for your reply! I just want to touch upon what you said at the end - "f you are looking for a comprehensive set of motif instances, I recommend using hit calls from this tool."

Does that mean this tools takes the seqlets identified by modisco (after doing the subsampling), and then searches over all given peaks of interest, reports the occurrence and position of said seqlets/motifs? Essentially taking the results of the subsampling and using it as a database so search over all peaks of interest?

**Comment by austintwang** [comment]
Hi Sidharth,

Big-picture-wise, yes. Though specifically, FiNeMo uses the CWM's (average contribution scores) to call hits, not the individual sequlets
