### ISSUE TITLE
error in 'finemo call-hits'

### ISSUE THREAD

**Issue by GGboy-Zzz** [austintwang/finemo_gpu#21]
hello,
  I tried to run motif hit calling using the '*.profile_scores.h5'. i extracted the sequences and contributions from it, yet I encountered an error in 'finemo call-hits', 
`Traceback (most recent call last):
  File "/home/zhuyong/miniconda3/envs/finemo/bin/finemo", line 8, in <module>
    sys.exit(cli())
  File "/home/zhuyong/package_repository/finemo_gpu-main/src/finemo/main.py", line 294, in cli
    call_hits(args.regions, args.peaks, args.modisco_h5, args.chrom_order, args.out_dir, 
  File "/home/zhuyong/package_repository/finemo_gpu-main/src/finemo/main.py", line 61, in call_hits
    raise ValueError(f"Input sequences of shape {sequences.shape} and/or " 
ValueError: Input sequences of shape (368638, 4, 1000) and/or input contributions of shape (368638, 4, 1000) are not compatible with region count of 368651`
I'm not sure this problem was caused by my peak file or regions file. Thanks a lot, any help is greatly appreciated!

**Comment by GGboy-Zzz** [comment]
I realized that the number of peaks in my regions file extracted from profile_score.h5 and narrow peaks file is inconsistent, but I'm sure when generated contribution score, I used the same narrow peaks file.

**Comment by austintwang** [comment]
Thank you for your patience! What might be happening is that ChromBPnet is filtering out some peaks. There should be a filtered peaks BED file outputted along with the contribution scores (see https://github.com/kundajelab/chrombpnet/wiki/Generate-contribution-score-bigwigs )

**Comment by GGboy-Zzz** [comment]
thanks for your answer! There does existed the filtered peaks BED file that I ignored in generate contribs outputs, I will try to run again.Thanks!

**Comment by 09oulin** [comment]
@austintwang @GGboy-Zzz 
Hello, thanks for your explanations. Now I have averaged the 5-fold counts_score.h5 and profile_scores.h5, so how can I get the final peaks BED file?  Does the filtered peaks BED files in 5-fold contribs outputs are the same? Could you please give me some advice? Thank you very much!!!
