### ISSUE TITLE
Error in  fine report - Data types mismatch during join operation

### ISSUE THREAD

**Issue by Yanbo-Xu** [austintwang/finemo_gpu#26]
Hi, I’m encountering a datatype mismatch issue while running finemo report. Here’s the traceback:

```
Traceback (most recent call last):
  File "/opt/conda/bin/finemo", line 8, in <module>
    sys.exit(cli())
  File "/kaggle/working/finemo_gpu/src/finemo/main.py", line 374, in cli
    report(args.regions, args.hits, args.modisco_h5, args.peaks, args.motifs_include, 
  File "/kaggle/working/finemo_gpu/src/finemo/main.py", line 162, in report
    report_data, report_df, cwms, trim_bounds = evaluation.tfmodisco_comparison(regions, hits_df, peaks_df, seqlets_df, motifs_df,
  File "/kaggle/working/finemo_gpu/src/finemo/evaluation.py", line 200, in tfmodisco_comparison
    .collect()
  File "/opt/conda/lib/python3.10/site-packages/polars/utils/deprecation.py", line 100, in wrapper
    return function(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1787, in collect
    return wrap_df(ldf.collect())
polars.exceptions.ComputeError: datatypes of join keys don't match - `start_untrimmed`: u32 on left does not match `start_untrimmed`: i64 on right
```

It appears that there’s a datatype mismatch between u32 and i64 in the start_untrimmed field during the join operation. I tried converting the data types manually but still encountered issues.

Could you please provide guidance on how to address this issue or if there is a potential fix for this mismatch in the code?

Thank you for your help!

**Comment by YanboXuu** [comment]
Furthermore,  I wanted to provide an update regarding the data types in the hits.tsv file. I have checked the data type for the start_untrimmed column, and it is confirmed to be int64. Here’s the relevant part of the data type output:

```
chr                       float64
start                       int64
end                         int64
start_untrimmed             int64
end_untrimmed               int64
motif_name                 object
hit_coefficient           float64
hit_coefficient_global    float64
hit_correlation           float64
hit_importance            float64
strand                     object
peak_name                 float64
peak_id                     int64
dtype: object
```

Despite this, the issue with the polars.exceptions.ComputeError: datatypes of join keys don't match - 'start_untrimmed': u32 on left does not match 'start_untrimmed': i64 on right persists.

**Comment by austintwang** [comment]
Hi Yanbo, apologies for the delay. It looks like the issue isn't with `hits.tsv` but rather with the seqlet data. Do you mind checking whether `seqlets_df` is empty?

**Comment by austintwang** [comment]
I've pushed a possible fix to the `dev` branch-- let me know whether this fixes your issue.

**Comment by Yanbo-Xu** [comment]
Hi Austin，I have some new questions:
1. Regarding the `seqlets_df` file you mentioned: Is it a data structure in the `.h5` output from TF-MoDISco? If so, I have checked my `.h5` file, and there is no `seqlets_df` present.
2. I also tried using the `dev` branch, but encountered a new error: 
```
Traceback (most recent call last):
  File "/opt/conda/bin/finemo", line 8, in <module>
    sys.exit(cli())
  File "/kaggle/working/finemo_gpu/src/finemo/main.py", line 374, in cli
    report(args.regions, args.hits, args.modisco_h5, args.peaks, args.motifs_include, 
  File "/kaggle/working/finemo_gpu/src/finemo/main.py", line 142, in report
    seqlets_df = data_io.load_modisco_seqlets(modisco_h5_path, peaks_df, half_width, modisco_half_width, lazy=True)
  File "/kaggle/working/finemo_gpu/src/finemo/data_io.py", line 364, in load_modisco_seqlets
    "seqlet_start": np.concatenate(start_lst, dtype=np.uint32),
TypeError: Cannot cast array data from dtype('int64') to dtype('uint32') according to the rule 'same_kind'
```

**Comment by Yanbo-Xu** [comment]
Hi Austin, I've resolved this issue. The problem is with the .bed file, which only contains some of the chromosomes. Thanks for your help!😃
