### ISSUE TITLE
 Relationship between hits in hits.tsv and input peaks range

### ISSUE THREAD

**Issue by Yanbo-Xu** [austintwang/finemo_gpu#28]
I noticed that some of the hits in the hits.tsv file appear to fall outside the range of the input peaks. Is the hits calling performed within a region surrounding the peaks rather than strictly limited to the precise boundaries of each peak? If my understanding is incorrect, a detailed explanation would be greatly appreciated. Thank you for your assistance!

**Comment by austintwang** [comment]
Hi Yanbo,

Yes, by default, finemo looks at 1000 bps around the peak summit (column 1 + column 10 [here](https://genome.ucsc.edu/FAQ/FAQformat.html#format12)) regardless of the interval size. You can adjust this using the `-w/--region-width` argument in the extract regions commands.  

Hope this helps!

**Comment by Yanbo-Xu** [comment]
Thanks Austin!!😊
